import type { Writable } from "svelte/store";
import { writable } from "svelte/store";
import type { Model } from "$lib/types";

export const models: Writable<Model[]> = writable([
  {
    includeModel: true,
    time: null,
    name: "Ada-002",
    embedding: [],
    modelName: "text-embedding-ada-002",
    modelType: "openai",
    useQuantized: false,
    similarity: null,
    synonyms: [],
    averageTime: null,
  },
  {
    includeModel: true,
    time: null,
    name: "Cohere",
    embedding: [],
    modelName: "embed-multilingual-v3.0",
    modelType: "cohere",
    useQuantized: false,
    similarity: null,
    synonyms: [],
    averageTime: null,
  },
  {
    includeModel: true,
    time: null,
    name: "OpenAI v3 small 512",
    embedding: [],
    modelName: "text-embedding-3-small",
    modelType: "openai",
    useQuantized: false,
    similarity: null,
    synonyms: [],
    averageTime: null,
    dimensions: 512,
  },
  {
    includeModel: true,
    time: null,
    name: "OpenAI v3 small 1536",
    embedding: [],
    modelName: "text-embedding-3-small",
    modelType: "openai",
    useQuantized: false,
    similarity: null,
    synonyms: [],
    averageTime: null,
    dimensions: 1536,
  },
  {
    includeModel: true,
    time: null,
    name: "OpenAI v3 Large 256",
    embedding: [],
    modelName: "text-embedding-3-large",
    modelType: "openai",
    useQuantized: false,
    similarity: null,
    synonyms: [],
    averageTime: null,
    dimensions: 256,
  },
  {
    includeModel: true,
    time: null,
    name: "OpenAI v3 Large 1024",
    embedding: [],
    modelName: "text-embedding-3-large",
    modelType: "openai",
    useQuantized: false,
    similarity: null,
    synonyms: [],
    averageTime: null,
    dimensions: 1024,
  },
  {
    includeModel: true,
    time: null,
    name: "OpenAI v3 Large 3072",
    embedding: [],
    modelName: "text-embedding-3-large",
    modelType: "openai",
    useQuantized: false,
    similarity: null,
    synonyms: [],
    averageTime: null,
    dimensions: 3072,
  },
]);
